### ISSUE TITLE
Cannot call method 'iterator' of undefined

### ISSUE THREAD

**Issue by jfromaniello** [rvagg/node-level-ttl#24]
I'm trying to do something like this:

```javascript
var db = levelup(__dirname + '/../cache.db', {valueEncoding: 'json'});
db =  sublevel(db);
var foobar = ttl(db.sublevel('foobar'))
```

but I get this error:

```
TypeError: Cannot call method 'iterator' of undefined
    at start (/my-project/node_modules/level-ttl/node_modules/level-spaces/node_modules/level-updown/level-updown.js:34:41)
    at new LevelUPDOWNIterator (/my-project/node_modules/level-ttl/node_modules/level-spaces/node_modules/level-updown/level-updown.js:38:12)
    at Object.iteratorFactory [as factory] (/my-project/node_modules/level-ttl/node_modules/level-spaces/node_modules/level-updown/level-updown.js:240:20)
    at Object.wrappedFactory [as factory] (/my-project/node_modules/level-ttl/node_modules/level-spaces/level-spaces.js:131:26)
    at LevelUPDOWN._iterator (/my-project/node_modules/level-ttl/node_modules/level-spaces/node_modules/level-updown/level-updown.js:249:14)
    at LevelUPDOWN.AbstractLevelDOWN.iterator (/my-project/node_modules/level-ttl/node_modules/level-spaces/node_modules/level-updown/node_modules/abstract-leveldown/abstract-leveldown.js:224:17)
    at /my-project/node_modules/levelup/lib/levelup.js:400:24
    at new ReadStream (/my-project/node_modules/levelup/lib/read-stream.js:68:22)
    at LevelUP.readStream.LevelUP.createReadStream (/my-project/node_modules/levelup/lib/levelup.js:396:10)
    at Timer.<anonymous> (/my-project/node_modules/level-ttl/level-ttl.js:19:17)
```

My package.json has this:

```
    "level-sublevel": "~6.4.4",
    "level-ttl": "~2.2.0",
    "leveldown": "~0.10.4",
    "levelup": "~0.18.6",
```

I've tried other combinations like:

```js
db =  ttl(sublevel(db));
```

and:

```js
db =  sublevel(ttl(db));
```

But I always get the same error.

**Comment by TehShrike** [comment]
Sadly, LevelTTL is not compatible with Sublevel, because Sublevel does not implement the full LevelUP interface.  See #15

**Comment by ralphtheninja** [comment]
@jfromaniello It might work with this PR https://github.com/rvagg/node-level-ttl/pull/25 , you could try the repo from @ekristen

**Comment by jfromaniello** [comment]
Thanks! Feel free to close this one
